### ISSUE TITLE
Initialization for self-contained components is not supported

### ISSUE THREAD

**Issue by Symbai** [BadRyuner/RPacked#1]
I've tried your tool on a .NET 8 console project published as self contained. It generated a 40mb file in "Output" folder together with a bootstrapper.runtimeconfig.json file. When I try to run the output file I get the following exception:

```
Initialization for self-contained components is not supported
thread 'main' panicked at src\main.rs:19:63:
called `Result::unwrap()` on an `Err` value: InvalidConfigFile
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is this a bug or are self contained apps really not supported? Also I noticed that native files like "vcruntime140_cor3.dll" which are required for the app to run, are ignored. Shouldn't they get copied to output folder as well? The packer writes which files it added to console but going through the list and copy each file which the packer ignored by hand to output folder feels odd.

**Comment by BadRyuner** [comment]
For self-contained applications, you can use a regular packer.
RPacked works according to the following principle:
1) Packing stage:
 - takes all .NET dlls (not native, there is no such support due to my lack of knowledge)
 - creates an array of bytes from them in the order in which they are loaded.
 - packs the data array using Brotli.
 - inserts the byte array into a special PESection in bootstrapper.exe
2) Startup stage of the exe:
 - The application unpacks the data array using Brotli.
 - It initializes the .NET environment using .NET Api. It loads the necessary clrcore.dll into the application according to app_runtimeconfig cfg. As far as I know selfcontained (without single file option) comes with its own coreclr.dll.
 - Loads all dlls into AppDomain using a special function that takes an array of bytes. This method only appeared in Net 8.
 - Calls the entry point and passes arguments (the latter does not work with file drops)
 - Hides coreclr.dll from dnspy/net dumper.

**Comment by Symbai** [comment]
Ah okay thanks for explaining. Then I was misunderstanding how it works, sorry.
